### ISSUE TITLE
error when applying patch

### ISSUE THREAD

**Issue by baritaklan123** [NyanCatTW1/robloxWineBuildGuide#23]
```/wine-tkg-git$ git apply roblox-wine-staging-v2.3.patch```
```error: unrecognized input```

**Comment by NyanCatTW1** [comment]
The current patch name is roblox-wine-staging-v2.4.patch. Try refreshing(F5) the guide on https://github.com/NyanCatTW1/robloxWineBuildGuide and retry.

**Comment by NyanCatTW1** [comment]
It's been a while since the last response, so I'll assume the issue has been resolved
Feel free to open a new issue if something else went wrong
