### ISSUE TITLE
package error

### ISSUE THREAD

**Issue by acopier** [NyanCatTW1/robloxWineBuildGuide#28]
Hello,
Im on KDE Neon latest version
I followed all steps and i get a package error with 32bit packages, i allowed them and the problem still exists

https://pastebin.com/is39fGWc

Please help
sorry some parts arent in english

**Comment by NyanCatTW1** [comment]
Umm, what's the current situation over there? Also, if you managed to fix the issue yourself, pleaee consider describing the solution here, as it might help some random dud in the future.

**Comment by acopier** [comment]
basically i distrohopped and im now on fedora
ubuntu has broken packages
