### ISSUE TITLE
New Roblox Launcher intentionally blocks linux Users

### ISSUE THREAD

**Issue by Luciogi** [NyanCatTW1/robloxWineBuildGuide#34]
https://www.gamingonlinux.com/2023/04/roblox-intentionally-blocking-linux-with-wine-in-their-new-update/

**Comment by Luciogi** [comment]
solution: 

https://user-images.githubusercontent.com/84625092/233833147-8e20d751-8bba-46e4-99ac-5304c8820d4c.mp4



Credit:https://www.gamingonlinux.com/2023/04/roblox-intentionally-blocking-linux-with-wine-in-their-new-update/comment_id=242605

**Comment by cp3p0n3** [comment]
this does not work, wine is still blocked

**Comment by Luciogi** [comment]
@cp3p0n3  for some odd reason disabling "wine hiding" option, still game works
Wine version: `wine-8.0.r1.g484054b2 ( TkG Staging Esync Fsync )`

Edit: new launcher is not available to all users

**Comment by Luciogi** [comment]
not working
https://www.gamingonlinux.com/2023/05/goodbye-to-roblox-on-linux-with-their-new-anti-cheat-and-wine-blocking//page=5#comments
