### ISSUE TITLE
Apply patch error

### ISSUE THREAD

**Issue by msmalik681** [NyanCatTW1/robloxWineBuildGuide#6]
this happens when I try to apply the patch on fedora 31.

```
[malik@localhost wine-tkg-git]$ git apply roblox-wine-staging-v2.patch
error: patch failed: wine-tkg-git/customization.cfg:94
error: wine-tkg-git/customization.cfg: patch does not apply
```

it worked about a month or two ago.

**Comment by e666666** [comment]
I will look up this issue on the weekend, in the meantime, alternatives are to either use old wine-tkg-git commits or use the prebuilt
